# Numpy Basics <hr style="border:2.5px solid rgba(94, 81, 2, 1) "></hr> 

<b>John Clark Dojoles</b>
<br>Computer Engineer

In [32]:
#%pip install numpy --upgrade
#%pip install scipy --upgrade

In [33]:
#%pip install --upgrade pip

In [34]:
# imports and packages
import numpy as np
from scipy import stats
from statistics import multimode

# 1D Array

In [35]:
my_array = [1,2,3]

In [36]:
type(my_array)

list

In [37]:
my_array = np.array([1,2,3])

In [38]:
np.shape(my_array)

(3,)

# 2D Array

In [39]:
my_array = np.array([
    [1,2,3],
    [4,5,6]
])
print (my_array)

[[1 2 3]
 [4 5 6]]


In [40]:
np.shape(my_array)

(2, 3)

In [41]:
my_array.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [42]:
trans_array = my_array.T

In [43]:
np.shape(trans_array)

(3, 2)

In [44]:
np.sum(trans_array, axis = 0)

array([ 6, 15])

In [45]:
np.sum(trans_array, axis = 1)

array([5, 7, 9])

# Measure of Central Tendency

In [46]:
resistance = np.array([
    [10.6, 9.1, 9.3, 9.8, 10.5, 10.4, 9.5, 11, 10.4, 3, 9.8], #Jaguar
    [10.1, 11, 9.1, 20, 9.2, 10.8, 9.9, 9.2, 9.1, 9.1, np.nan] #Panther
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [47]:
np.shape(resistance)

(2, 11)

In [48]:
resistance.T

array([[10.6, 10.1],
       [ 9.1, 11. ],
       [ 9.3,  9.1],
       [ 9.8, 20. ],
       [10.5,  9.2],
       [10.4, 10.8],
       [ 9.5,  9.9],
       [11. ,  9.2],
       [10.4,  9.1],
       [ 3. ,  9.1],
       [ 9.8,  nan]])

In [49]:
np.mean(resistance, axis=0)

array([10.35, 10.05,  9.2 , 14.9 ,  9.85, 10.6 ,  9.7 , 10.1 ,  9.75,
        6.05,   nan])

In [50]:
np.mean(resistance, axis=1)

array([9.4, nan])

In [51]:
# Mean
np.nanmean(resistance, axis=1)

array([ 9.4 , 10.75])

In [52]:
jag_mean = np.nanmean(resistance, axis=1)[0]
pan_mean = np.nanmean(resistance, axis=1)[1]

print(f'Jaguar Mean = {jag_mean:.2f} ohms')
print(f'Panther Mean = {pan_mean:.2f} ohms')

Jaguar Mean = 9.40 ohms
Panther Mean = 10.75 ohms


In [53]:
# Meidan
np.nanmedian(resistance, axis=1)


array([9.8 , 9.55])

In [54]:
jag_median = np.nanmedian(resistance, axis=1)[0]
pan_median = np.nanmedian(resistance, axis=1)[1]

print (f'Jaguar Median = {jag_median:.2f} ohms')
print (f'Panther Median = {pan_median:.2f} ohms')

Jaguar Median = 9.80 ohms
Panther Median = 9.55 ohms


In [55]:
# Mode
stats.mode(resistance, axis=1)

ModeResult(mode=array([9.8, 9.1]), count=array([2, 3]))

In [56]:
my_array = [1, 1, 2, 2, 3, 4, 5]
multimode(my_array)

[1, 2]

In [57]:
jag_res = resistance[0]

print("Jaguar mode:")
for i in multimode(jag_res):
    print(f'{i} ohms')

Jaguar mode:
9.8 ohms
10.4 ohms


In [58]:
pan_res = resistance[1]

print("Panther mode:")
for i in multimode(pan_res):
    print(f'{i} ohms')

Panther mode:
9.1 ohms


# Measures of Variability

In [59]:
# Jaguar vs Panther
resistance = np.array([
    [10.6, 9.1, 9.3, 9.8, 10.5, 10.4, 9.5, 11, 10.4, 3, 9.8],
    [10.1, 11, 9.1, 20, 9.2, 10.8, 9.9, 9.2, 9.1, 9.1, np.nan]
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [60]:
# Range
res_max = np.nanmax(resistance, axis=1)
res_min = np.nanmin(resistance, axis=1)

res_range = res_max - res_min
res_range

array([ 8. , 10.9])

In [61]:
print(f'Jaguar_range = {res_range[0]:.2f} ohms')
print(f'Panther_range = {res_range[1]:.2f} ohms')

Jaguar_range = 8.00 ohms
Panther_range = 10.90 ohms


In [62]:
# 1st Quartile
res_Q1 = np.nanpercentile(resistance, 25, axis=1)
res_Q1

array([9.4  , 9.125])

In [63]:
# 2nd Quartile
res_Q2 = np.nanpercentile(resistance, 50, axis=1)
res_Q2

array([9.8 , 9.55])

In [64]:
# 3rd Quartile
res_Q3 = np.nanpercentile(resistance, 75, axis=1)
res_Q3

array([10.45 , 10.625])

In [65]:
# IQR
print(f'Jaguar_IQR = {res_Q3[0] - res_Q1[0]:.2f} ohms')
print(f'Panther_IQR = {res_Q3[1] - res_Q1[1]:.2f} ohms')

Jaguar_IQR = 1.05 ohms
Panther_IQR = 1.50 ohms


In [66]:
# Variance
res_var = np.nanvar(resistance, axis=1)
res_var

array([4.41818182, 9.9745    ])

In [67]:
print(f'Jaguar Variance = {res_var[0]:.2f} ohms^2')
print(f'Panther Variance = {res_var[1]:.2f} ohms^2')

Jaguar Variance = 4.42 ohms^2
Panther Variance = 9.97 ohms^2


In [68]:
# Standard Deviation
res_std = np.nanstd(resistance, axis=1)
res_std

array([2.10194715, 3.15824318])

In [69]:
print(f'Jaguar Standard Deviation = {res_std[0]:.2f} ohms')
print(f'Panther Standard Deviation = {res_std[1]:.2f} ohms')

Jaguar Standard Deviation = 2.10 ohms
Panther Standard Deviation = 3.16 ohms
