# Numpy <hr style="border:2.5px solid rgba(94, 81, 2, 1) "></hr> 

<b>John Clark Dojoles</b>
Computer Engineer

# 1D Array

In [19]:
# imports and packages
import numpy as np

In [20]:
my_array = [1,2,3]

In [21]:
type(my_array)

list

In [22]:
my_array = np.array([1,2,3])

In [23]:
np.shape(my_array)

(3,)

# 2D Array

In [24]:
my_array = np.array([
    [1,2,3],
    [4,5,6]
])
print (my_array)

[[1 2 3]
 [4 5 6]]


In [25]:
np.shape(my_array)

(2, 3)

In [26]:
my_array.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [27]:
trans_array = my_array.T

In [28]:
np.shape(trans_array)

(3, 2)

In [29]:
np.sum(trans_array, axis = 0)

array([ 6, 15])

In [30]:
np.sum(trans_array, axis = 1)

array([5, 7, 9])

# Measure of Central Tendency

In [37]:
resistance = np.array([
    [10.6, 9.1, 9.3, 9.8, 10.5, 10.4, 9.5, 11, 10.4, 3, 9.8], #Jaguar
    [10.1, 11, 9.1, 20, 9.2, 10.8, 9.9, 9.2, 9.1, 9.1, np.nan] #Panther
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [44]:
trans_array = resistance.T

In [47]:
np.nanmean(trans_array, axis = 0)

array([ 9.4 , 10.75])